blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Ideas
    url: https://github.com/vicentealvarezasencio/ui-design-cc/discussions/categories/ideas
    about: Share ideas for new features or improvements
  - name: ğŸ™ Q&A
    url: https://github.com/vicentealvarezasencio/ui-design-cc/discussions/categories/q-a
    about: Ask the community for help
  - name: ğŸ™Œ Show and Tell
    url: https://github.com/vicentealvarezasencio/ui-design-cc/discussions/categories/show-and-tell
    about: Show off what you've built with ui-design-cc
  - name: ğŸ’¬ General
    url: https://github.com/vicentealvarezasencio/ui-design-cc/discussions/categories/general
    about: Chat about anything related to the project
