blank_issues_enabled: false
contact_links:
  - name: Discussions - Ideas & Questions
    url: https://github.com/vicentealvarezasencio/ui-design-cc/discussions
    about: Have an idea or question? Start a discussion!
  - name: Discussions - Show & Tell
    url: https://github.com/vicentealvarezasencio/ui-design-cc/discussions/categories/show-and-tell
    about: Share what you've built with ui-design-cc
